spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/wetube?currentSchema=user_service
    username: admin
    password: admin123

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka
