server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/wetube?currentSchema=user_service
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
      password: admin123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

security:
  jwt:
    secret: a111396840caddbdd1b160c64045ebb68baf11ba0cf4996e8526ceb3c67d570b

gateway:
  token: mBuIFTo+SjyJOXeNN75zeGIUD6InWfcgwoRp2llZXgs=